name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
      - name: Install platform
        run: |
          arduino-cli core install arduino:avr
      - name: Compile Sketch
        working-directory: ./midi_rgb
        # run: ARDUINO_DIRECTORIES_USER=$GITHUB_WORKSPACE/microcontroller arduino-cli config dump
        run: ARDUINO_DIRECTORIES_USER=$GITHUB_WORKSPACE/midi_rgb arduino-cli compile -b arduino:avr:mega
      # - name: Upload bin
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ matrix.core_a}}_${{ matrix.core_b }}_${{ matrix.board }}_${{ matrix.apn }}
      #     path: ./microcontroller/build/${{ matrix.core_a}}.${{ matrix.core_b }}.${{ matrix.board }}/microcontroller.ino.bin